package com.missoandfriends.jsonapi.services;

import java.util.HashMap;
import java.util.Map;

public class CountryStateAbbrService {
	
	public static final Map<String, String> countryToAlpha3 = new HashMap<>();
	public static final Map<String, String> alpha3ToCountry = new HashMap<>();
	public static final Map<String, String> stateAbbToName  = new HashMap<>();
	public static final Map<String, String> stateNameToAbbr = new HashMap<>();
	
	static {
		countryToAlpha3.put("Afghanistan", "AFG");
		countryToAlpha3.put("Aland Islands", "ALA");
		countryToAlpha3.put("Albania", "ALB");
		countryToAlpha3.put("Algeria", "DZA");
		countryToAlpha3.put("American Samoa", "ASM");
		countryToAlpha3.put("Andorra", "AND");
		countryToAlpha3.put("Angola", "AGO");
		countryToAlpha3.put("Anguilla", "AIA");
		countryToAlpha3.put("Antarctica", "ATA");
		countryToAlpha3.put("Antigua and Barbuda", "ATG");
		countryToAlpha3.put("Argentina", "ARG");
		countryToAlpha3.put("Armenia", "ARM");
		countryToAlpha3.put("Aruba", "ABW");
		countryToAlpha3.put("Australia", "AUS");
		countryToAlpha3.put("Austria", "AUT");
		countryToAlpha3.put("Azerbaijan", "AZE");
		countryToAlpha3.put("Bahamas", "BHS");
		countryToAlpha3.put("Bahrain", "BHR");
		countryToAlpha3.put("Bangladesh", "BGD");
		countryToAlpha3.put("Barbados", "BRB");
		countryToAlpha3.put("Belarus", "BLR");
		countryToAlpha3.put("Belgium", "BEL");
		countryToAlpha3.put("Belize", "BLZ");
		countryToAlpha3.put("Benin", "BEN");
		countryToAlpha3.put("Bermuda", "BMU");
		countryToAlpha3.put("Bhutan", "BTN");
		countryToAlpha3.put("Bolivia", "BOL");
		countryToAlpha3.put("Bosnia and Herzegovina", "BIH");
		countryToAlpha3.put("Botswana", "BWA");
		countryToAlpha3.put("Bouvet Island", "BVT");
		countryToAlpha3.put("Brazil", "BRA");
		countryToAlpha3.put("British Virgin Islands", "VGB");
		countryToAlpha3.put("British Indian Ocean Territory", "IOT");
		countryToAlpha3.put("Brunei Darussalam", "BRN");
		countryToAlpha3.put("Bulgaria", "BGR");
		countryToAlpha3.put("Burkina Faso", "BFA");
		countryToAlpha3.put("Burundi", "BDI");
		countryToAlpha3.put("Cambodia", "KHM");
		countryToAlpha3.put("Cameroon", "CMR");
		countryToAlpha3.put("Canada", "CAN");
		countryToAlpha3.put("Cape Verde", "CPV");
		countryToAlpha3.put("Cayman Islands", "CYM");
		countryToAlpha3.put("Central African Republic", "CAF");
		countryToAlpha3.put("Chad", "TCD");
		countryToAlpha3.put("Chile", "CHL");
		countryToAlpha3.put("China", "CHN");
		countryToAlpha3.put("Hong Kong, SAR China", "HKG");
		countryToAlpha3.put("Macao, SAR China", "MAC");
		countryToAlpha3.put("Christmas Island", "CXR");
		countryToAlpha3.put("Cocos (Keeling) Islands", "CCK");
		countryToAlpha3.put("Colombia", "COL");
		countryToAlpha3.put("Comoros", "COM");
		countryToAlpha3.put("Congo (Brazzaville)", "COG");
		countryToAlpha3.put("Congo, (Kinshasa)", "COD");
		countryToAlpha3.put("Cook Islands", "COK");
		countryToAlpha3.put("Costa Rica", "CRI");
		countryToAlpha3.put("Côte d'Ivoire", "CIV");
		countryToAlpha3.put("Croatia", "HRV");
		countryToAlpha3.put("Cuba", "CUB");
		countryToAlpha3.put("Cyprus", "CYP");
		countryToAlpha3.put("Czech Republic", "CZE");
		countryToAlpha3.put("Denmark", "DNK");
		countryToAlpha3.put("Djibouti", "DJI");
		countryToAlpha3.put("Dominica", "DMA");
		countryToAlpha3.put("Dominican Republic", "DOM");
		countryToAlpha3.put("Ecuador", "ECU");
		countryToAlpha3.put("Egypt", "EGY");
		countryToAlpha3.put("El Salvador", "SLV");
		countryToAlpha3.put("Equatorial Guinea", "GNQ");
		countryToAlpha3.put("Eritrea", "ERI");
		countryToAlpha3.put("Estonia", "EST");
		countryToAlpha3.put("Ethiopia", "ETH");
		countryToAlpha3.put("Falkland Islands (Malvinas)", "FLK");
		countryToAlpha3.put("Faroe Islands", "FRO");
		countryToAlpha3.put("Fiji", "FJI");
		countryToAlpha3.put("Finland", "FIN");
		countryToAlpha3.put("France", "FRA");
		countryToAlpha3.put("French Guiana", "GUF");
		countryToAlpha3.put("French Polynesia", "PYF");
		countryToAlpha3.put("French Southern Territories", "ATF");
		countryToAlpha3.put("Gabon", "GAB");
		countryToAlpha3.put("Gambia", "GMB");
		countryToAlpha3.put("Georgia", "GEO");
		countryToAlpha3.put("Germany", "DEU");
		countryToAlpha3.put("Ghana", "GHA");
		countryToAlpha3.put("Gibraltar", "GIB");
		countryToAlpha3.put("Greece", "GRC");
		countryToAlpha3.put("Greenland", "GRL");
		countryToAlpha3.put("Grenada", "GRD");
		countryToAlpha3.put("Guadeloupe", "GLP");
		countryToAlpha3.put("Guam", "GUM");
		countryToAlpha3.put("Guatemala", "GTM");
		countryToAlpha3.put("Guernsey", "GGY");
		countryToAlpha3.put("Guinea", "GIN");
		countryToAlpha3.put("Guinea-Bissau", "GNB");
		countryToAlpha3.put("Guyana", "GUY");
		countryToAlpha3.put("Haiti", "HTI");
		countryToAlpha3.put("Heard and Mcdonald Islands", "HMD");
		countryToAlpha3.put("Holy See (Vatican City State)", "VAT");
		countryToAlpha3.put("Honduras", "HND");
		countryToAlpha3.put("Hungary", "HUN");
		countryToAlpha3.put("Iceland", "ISL");
		countryToAlpha3.put("India", "IND");
		countryToAlpha3.put("Indonesia", "IDN");
		countryToAlpha3.put("Iran, Islamic Republic of", "IRN");
		countryToAlpha3.put("Iraq", "IRQ");
		countryToAlpha3.put("Ireland", "IRL");
		countryToAlpha3.put("Isle of Man", "IMN");
		countryToAlpha3.put("Israel", "ISR");
		countryToAlpha3.put("Italy", "ITA");
		countryToAlpha3.put("Jamaica", "JAM");
		countryToAlpha3.put("Japan", "JPN");
		countryToAlpha3.put("Jersey", "JEY");
		countryToAlpha3.put("Jordan", "JOR");
		countryToAlpha3.put("Kazakhstan", "KAZ");
		countryToAlpha3.put("Kenya", "KEN");
		countryToAlpha3.put("Kiribati", "KIR");
		countryToAlpha3.put("Korea (North)", "PRK");
		countryToAlpha3.put("Korea (South)", "KOR");
		countryToAlpha3.put("Kuwait", "KWT");
		countryToAlpha3.put("Kyrgyzstan", "KGZ");
		countryToAlpha3.put("Lao PDR", "LAO");
		countryToAlpha3.put("Latvia", "LVA");
		countryToAlpha3.put("Lebanon", "LBN");
		countryToAlpha3.put("Lesotho", "LSO");
		countryToAlpha3.put("Liberia", "LBR");
		countryToAlpha3.put("Libya", "LBY");
		countryToAlpha3.put("Liechtenstein", "LIE");
		countryToAlpha3.put("Lithuania", "LTU");
		countryToAlpha3.put("Luxembourg", "LUX");
		countryToAlpha3.put("Macedonia, Republic of", "MKD");
		countryToAlpha3.put("Madagascar", "MDG");
		countryToAlpha3.put("Malawi", "MWI");
		countryToAlpha3.put("Malaysia", "MYS");
		countryToAlpha3.put("Maldives", "MDV");
		countryToAlpha3.put("Mali", "MLI");
		countryToAlpha3.put("Malta", "MLT");
		countryToAlpha3.put("Marshall Islands", "MHL");
		countryToAlpha3.put("Martinique", "MTQ");
		countryToAlpha3.put("Mauritania", "MRT");
		countryToAlpha3.put("Mauritius", "MUS");
		countryToAlpha3.put("Mayotte", "MYT");
		countryToAlpha3.put("Mexico", "MEX");
		countryToAlpha3.put("Micronesia, Federated States of", "FSM");
		countryToAlpha3.put("Moldova", "MDA");
		countryToAlpha3.put("Monaco", "MCO");
		countryToAlpha3.put("Mongolia", "MNG");
		countryToAlpha3.put("Montenegro", "MNE");
		countryToAlpha3.put("Montserrat", "MSR");
		countryToAlpha3.put("Morocco", "MAR");
		countryToAlpha3.put("Mozambique", "MOZ");
		countryToAlpha3.put("Myanmar", "MMR");
		countryToAlpha3.put("Namibia", "NAM");
		countryToAlpha3.put("Nauru", "NRU");
		countryToAlpha3.put("Nepal", "NPL");
		countryToAlpha3.put("Netherlands", "NLD");
		countryToAlpha3.put("Netherlands Antilles", "ANT");
		countryToAlpha3.put("New Caledonia", "NCL");
		countryToAlpha3.put("New Zealand", "NZL");
		countryToAlpha3.put("Nicaragua", "NIC");
		countryToAlpha3.put("Niger", "NER");
		countryToAlpha3.put("Nigeria", "NGA");
		countryToAlpha3.put("Niue", "NIU");
		countryToAlpha3.put("Norfolk Island", "NFK");
		countryToAlpha3.put("Northern Mariana Islands", "MNP");
		countryToAlpha3.put("Norway", "NOR");
		countryToAlpha3.put("Oman", "OMN");
		countryToAlpha3.put("Pakistan", "PAK");
		countryToAlpha3.put("Palau", "PLW");
		countryToAlpha3.put("Palestinian Territory", "PSE");
		countryToAlpha3.put("Panama", "PAN");
		countryToAlpha3.put("Papua New Guinea", "PNG");
		countryToAlpha3.put("Paraguay", "PRY");
		countryToAlpha3.put("Peru", "PER");
		countryToAlpha3.put("Philippines", "PHL");
		countryToAlpha3.put("Pitcairn", "PCN");
		countryToAlpha3.put("Poland", "POL");
		countryToAlpha3.put("Portugal", "PRT");
		countryToAlpha3.put("Puerto Rico", "PRI");
		countryToAlpha3.put("Qatar", "QAT");
		countryToAlpha3.put("Réunion", "REU");
		countryToAlpha3.put("Romania", "ROU");
		countryToAlpha3.put("Russian Federation", "RUS");
		countryToAlpha3.put("Rwanda", "RWA");
		countryToAlpha3.put("Saint-Barthélemy", "BLM");
		countryToAlpha3.put("Saint Helena", "SHN");
		countryToAlpha3.put("Saint Kitts and Nevis", "KNA");
		countryToAlpha3.put("Saint Lucia", "LCA");
		countryToAlpha3.put("Saint-Martin (French part)", "MAF");
		countryToAlpha3.put("Saint Pierre and Miquelon", "SPM");
		countryToAlpha3.put("Saint Vincent and Grenadines", "VCT");
		countryToAlpha3.put("Samoa", "WSM");
		countryToAlpha3.put("San Marino", "SMR");
		countryToAlpha3.put("Sao Tome and Principe", "STP");
		countryToAlpha3.put("Saudi Arabia", "SAU");
		countryToAlpha3.put("Senegal", "SEN");
		countryToAlpha3.put("Serbia", "SRB");
		countryToAlpha3.put("Seychelles", "SYC");
		countryToAlpha3.put("Sierra Leone", "SLE");
		countryToAlpha3.put("Singapore", "SGP");
		countryToAlpha3.put("Slovakia", "SVK");
		countryToAlpha3.put("Slovenia", "SVN");
		countryToAlpha3.put("Solomon Islands", "SLB");
		countryToAlpha3.put("Somalia", "SOM");
		countryToAlpha3.put("South Africa", "ZAF");
		countryToAlpha3.put("South Georgia and the South Sandwich Islands", "SGS");
		countryToAlpha3.put("South Sudan", "SSD");
		countryToAlpha3.put("Spain", "ESP");
		countryToAlpha3.put("Sri Lanka", "LKA");
		countryToAlpha3.put("Sudan", "SDN");
		countryToAlpha3.put("Suriname", "SUR");
		countryToAlpha3.put("Svalbard and Jan Mayen Islands", "SJM");
		countryToAlpha3.put("Swaziland", "SWZ");
		countryToAlpha3.put("Sweden", "SWE");
		countryToAlpha3.put("Switzerland", "CHE");
		countryToAlpha3.put("Syrian Arab Republic (Syria)", "SYR");
		countryToAlpha3.put("Taiwan, Republic of China", "TWN");
		countryToAlpha3.put("Tajikistan", "TJK");
		countryToAlpha3.put("Tanzania, United Republic of", "TZA");
		countryToAlpha3.put("Thailand", "THA");
		countryToAlpha3.put("Timor-Leste", "TLS");
		countryToAlpha3.put("Togo", "TGO");
		countryToAlpha3.put("Tokelau", "TKL");
		countryToAlpha3.put("Tonga", "TON");
		countryToAlpha3.put("Trinidad and Tobago", "TTO");
		countryToAlpha3.put("Tunisia", "TUN");
		countryToAlpha3.put("Turkey", "TUR");
		countryToAlpha3.put("Turkmenistan", "TKM");
		countryToAlpha3.put("Turks and Caicos Islands", "TCA");
		countryToAlpha3.put("Tuvalu", "TUV");
		countryToAlpha3.put("Uganda", "UGA");
		countryToAlpha3.put("Ukraine", "UKR");
		countryToAlpha3.put("United Arab Emirates", "ARE");
		countryToAlpha3.put("United Kingdom", "GBR");
		countryToAlpha3.put("United States of America", "USA");
		countryToAlpha3.put("US Minor Outlying Islands", "UMI");
		countryToAlpha3.put("Uruguay", "URY");
		countryToAlpha3.put("Uzbekistan", "UZB");
		countryToAlpha3.put("Vanuatu", "VUT");
		countryToAlpha3.put("Venezuela (Bolivarian Republic)", "VEN");
		countryToAlpha3.put("Viet Nam", "VNM");
		countryToAlpha3.put("Virgin Islands, US", "VIR");
		countryToAlpha3.put("Wallis and Futuna Islands", "WLF");
		countryToAlpha3.put("Western Sahara", "ESH");
		countryToAlpha3.put("Yemen", "YEM");
		countryToAlpha3.put("Zambia", "ZMB");
		countryToAlpha3.put("Zimbabwe", "ZWE");
		
		for (final String key: countryToAlpha3.keySet()) {
			alpha3ToCountry.put(countryToAlpha3.get(key), key);
		}
		
		stateAbbToName.put("AL", "Alabama");
		stateAbbToName.put("AK", "Alaska");
		stateAbbToName.put("AZ", "Arizona");
		stateAbbToName.put("AR", "Arkansas");
		stateAbbToName.put("CA", "California");
		stateAbbToName.put("CO", "Colorado");
		stateAbbToName.put("CT", "Connecticut");
		stateAbbToName.put("DE", "Delaware");
		stateAbbToName.put("FL", "Florida");
		stateAbbToName.put("GA", "Georgia");
		stateAbbToName.put("HI", "Hawaii");
		stateAbbToName.put("ID", "Idaho");
		stateAbbToName.put("IL", "Illinois");
		stateAbbToName.put("IN", "Indiana");
		stateAbbToName.put("IA", "Iowa");
		stateAbbToName.put("KS", "Kansas");
		stateAbbToName.put("KY", "Kentucky");
		stateAbbToName.put("LA", "Louisiana");
		stateAbbToName.put("ME", "Maine");
		stateAbbToName.put("MD", "Maryland");
		stateAbbToName.put("MA", "Massachusetts");
		stateAbbToName.put("MI", "Michigan");
		stateAbbToName.put("MN", "Minnesota");
		stateAbbToName.put("MS", "MISSISSIPPI");
		stateAbbToName.put("MO", "Missouri");
		stateAbbToName.put("MT", "Montana");
		stateAbbToName.put("NE", "Nebraska");
		stateAbbToName.put("NV", "Nevada");
		stateAbbToName.put("NH", "New Hampshire");
		stateAbbToName.put("NJ", "New Jersey");
		stateAbbToName.put("NM", "New Mexico");
		stateAbbToName.put("NY", "New York");
		stateAbbToName.put("NC", "North Carolina");
		stateAbbToName.put("ND", "North Dakota");
		stateAbbToName.put("OH", "Ohio");
		stateAbbToName.put("OK", "Oklahoma");
		stateAbbToName.put("OR", "Oregon");
		stateAbbToName.put("PA", "Pennsylvania");
		stateAbbToName.put("RI", "Rhode Island");
		stateAbbToName.put("SC", "South Carolina");
		stateAbbToName.put("SD", "South Dakota");
		stateAbbToName.put("TN", "Tennessee");
		stateAbbToName.put("TX", "Texas");
		stateAbbToName.put("UT", "Utah");
		stateAbbToName.put("VT", "Vermont");
		stateAbbToName.put("VA", "Virginia");
		stateAbbToName.put("WA", "Washington");
		stateAbbToName.put("WV", "West Virginia");
		stateAbbToName.put("WI", "Wisconsin");
		stateAbbToName.put("WY", "Wyoming");
		
		for (final String key: stateAbbToName.keySet()) {
			stateNameToAbbr.put(stateAbbToName.get(key), key);
		}
	}
	
}
